services:

  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf

  spring-boot-app:
    build: ./kwik-beheer
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      - MQTT_BROKER_URL=tcp://mqtt-broker:1883
    depends_on:
      - mqtt-broker

  #   MQTT Thermometers
  thermometer-bed:
    build: ./thermometer
    container_name: mock-thermometer
    environment:
      - BUILDING=home
      - ROOM=bedroom
    depends_on:
      - mqtt-broker
  thermometer-bath:
    build: ./thermometer
    container_name: thermometer-bath
    environment:
      - BUILDING=home
      - ROOM=bathroom
    depends_on:
      - mqtt-broker

  thermometer-living:
    build: ./thermometer
    container_name: thermometer-living
    environment:
      - BUILDING=home
      - ROOM=livingroom
    depends_on:
      - mqtt-broker

  thermometer-dorm:
    build: ./thermometer
    container_name: thermometer-dorm
    environment:
      - BUILDING=dorm
      - ROOM=dormroom
    depends_on:
      - mqtt-broker

